[tool.poetry]
name = "phonebook"
version = "0.1.0"
description = ""
authors = ["Mikhail Zykov <paradoxm@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
